config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :microposts,          only: [:create, :destroy]

  resources :posts do
    resources :comments
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Social Network</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
  This is the About page for the Social Network application developped by <a href="www.jaafar-el-alamy.com">Jaafar EL ALAMY.</a>
</p>

  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  This is the Contact Page.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Social Network</title>
  </head>
  <body>
    <h1>Help</h1>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Social Network</title>
  </head>
  <body>
 <% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Social Network</h1>

  <h2>
    This is the home page for the Social Network Web Application
  </h2>

  <%= link_to "Sign Up ", signup_path, class: "btn btn-lg btn-primary" %><br> <br>
  <%= link_to "Sign In", login_path, class: "btn btn-lg btn-primary" %>

</div>

<center><%= link_to image_tag("social.png", alt: "Rails logo"),
            'http://www.jaafar-el-alamy.com/' %></center>
<% end %>
</body>
</html>